<?php

declare(strict_types=1);

namespace App\DAO;

use ArrayIterator;
use ArrayObject;

/**
 * @extends ArrayObject<int,PageInfo>
 */
class SearchResults extends ArrayObject
{
    /**
     * @param PageInfo[]|mixed[] $array
     * @param class-string $iteratorClass
     */
    public function __construct(array $array = [], int $flags = 0, string $iteratorClass = ArrayIterator::class)
    {
        foreach ($array as $key => $value) {
            $array[$key] = $this->normalize($value);
        }
        parent::__construct($array, $flags, $iteratorClass);
    }
    public function offsetSet(mixed $key, mixed $value): void
    {
        $value = $this->normalize($value);
        parent::offsetSet($key, $value); // TODO: Change the autogenerated stub
    }

    public function offsetGet(mixed $key): ?PageInfo
    {
        return parent::offsetGet($key);
    }

    /**
     * @param mixed $value
     * @throws \InvalidArgumentException
     */
    protected function normalize(mixed $value): PageInfo
    {
        if (is_array($value)) {
            $value = PageInfo::fromArray($value);
        }
        if (!$value instanceof PageInfo) {
            throw new \InvalidArgumentException('$value must be a PageInfo object');
        }
        return $value;
    }

}
