<?php

namespace App\DAO;

use ArrayIterator;
use ArrayObject;

class SearchResults extends ArrayObject
{

    public function __construct(array $array = [], int $flags = 0, ?string $iteratorClass = ArrayIterator::class) {
        foreach ($array as $key => $value) {
            $array[$key]=$this->normalize($value);
        }
        bdump($array);
        parent::__construct($array, $flags, $iteratorClass);
    }
    public function offsetSet(mixed $key, mixed $value): void
    {

        parent::offsetSet($key, $value); // TODO: Change the autogenerated stub
    }

    public function offsetGet(mixed $key): PageInfo {
        return parent::offsetGet($key);
    }

    /**
     * @param mixed $value
     * @throws \InvalidArgumentException
     */
    protected function normalize(mixed $value): PageInfo
    {
        if(is_array($value)) {
            $value = PageInfo::fromArray($value);
        }
        if(!$value instanceof PageInfo) {
            throw new \InvalidArgumentException('$value must be a PageInfo object');
        }
        return $value;
    }

}